### ISSUE TITLE
Café

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#277]
Hey, we are going to start using the worker system in Hilbert café again and it needs some refactoring.
### TODO
- [x] Add model `CafeWorker`
- [x] Rename models (`CafeWork => CafeShift`, `CafeWorkCouncil => CafeWorkerCouncil`)
- [x] Competition: allow different groups to compete (not only `Councils`), perhaps it should be `CafeWorkerGroup`? #154 
- [x] Add tools and views for the worker competition and group competition.
- [x] Rework views
- [x] Localize views
- [ ] Ability to display Holidays in work schedule. #13 
- [x] Add ability to create CafeShift for one working day.
- [ ] Allow administrators to see full Highscore list
- [x] Don't allow to work at two shifts which are at the same time.
- [ ] Don't allow signup on old shifts (except for administrators)
- [ ] Better views for listing all workers, better filtering for `overview`.

**Comment by jforberg** [comment]
Suggestion: To keep it simple, just use a string column as the "Council" selector. Preload it with the names of current councils. Show the list of current groups but allow users to enter any text string as their group. Expire the strings after ~1 year. Then you don't need any models etc. just a few very simple SQL queries.

**Comment by jforberg** [comment]
The question you should be asking yourself is "do I need to track any information about a group other than its name?" If no then CafeWorkerGroup is just a glorified String class and probably unnecessary. The relevant design principle here is YAGNI. http://c2.com/cgi/wiki?YouArentGonnaNeedIt

**Comment by davidwessman** [comment]
Should you add some feature to merge someones tag `pryl` into `Prylmästeriet` as well?

**Comment by jforberg** [comment]
You could. But it would be easier to just give a select with the existing tags, then a button to add a new tag.

If they can't manage to select the correct team, they have lost the competition :)

**Comment by davidwessman** [comment]
When moving to a new table-name, is it worth to be more gentle and
- create a fresh table and start using this in the code.
- Do a rake-task or manual transfer of data. 
- When completely transfered, create a migration to dump old table.

Or just do a migration with `rename_table`?

**Comment by davidwessman** [comment]
@jforberg They would like people to be able to compete for multiple groups as well.
Is it possible to query for a string with multiple groups? Or query and get all groups.

**Comment by jforberg** [comment]
Well, there is a point where you can deny the order because it's too much work. Or save it for version 2.0. At this point I think it would be completely reasonable to ship just single teams now, and implement multi-team support later. In the best case perhaps they find that it works well that way and we never have to implement multi-teams.

Re tables: Depends. If you are just moving the table (for some good reason I hope) then absolutely just rename. If you are doing some more complex data conversion then you can do it as a separate migration. Rake tasks are not appropriate for this purpose IMO. Although of course the migration can be run through rake.

**Comment by davidwessman** [comment]
Just merged this to Stage, gonna get the Cafe-people to try it out a bit 😄 

I wanna keep the data for the old table `cafe_works` and migrate part of it to `cafe_shifts` and part to `cafe_workers`. I feel more sure leaving all the data in the `cafe_works` table, add the new tables, move the data by console or a rake task. Then clean up all the old code and drop the tables.

I do not want to move the data within a migration, leaving the old model `CafeWork` in a migration file.

**Comment by jforberg** [comment]
Using the console is always a possiblity, since you can then handle some corner cases that you may not have thought about. But it would be good if you also wrote a migration afterwards (when you know exactly what has to be done). So it can be used for all testing databases, etc.

What do you mean, leaving cafework? Migrations don't deal with models, only tables.

I don't think plain rake tasks are appropriate for this.

**Comment by jforberg** [comment]
Actually, the best way to do it would be:

1. Download the production database and set it up locally.
2. Do the migration by hand in the console
3. Verify that everything work
4. Write the same commands into a migration
5. Optionally reload the database and check that the migration actually works
6. Upload to the server and run the migration

Then you would be 100% sure that you have a good migration, which works with the production data.

**Comment by davidwessman** [comment]
I think this is where my doubts of data in migrations is coming from.
https://robots.thoughtbot.com/data-migrations-in-rails

**Comment by jforberg** [comment]
Let me retort then :) Warning rant.

> migrations files will stay in the db/migrate directory for posterity, and will run whenever a new developer sets their local development environment. 

No. New environments are set up with db:schema:load, not db:migrate. Migrations are for migrating existing environments.

> future changes to a class and its logic can easily break the migration later on.

How? Migrations don't have any awareness of classes or their logic.

> those data migrations might be ignored by future developers if instead of running rake db:migrate the developers run rake db:schema:load or rake db:reset. Both commands merely load the latest version of the database structure using the schema.rb file without touching the migrations

Well, db:schema:load and db:reset both truncate the entire database. So there is no data at all after they are run.

> Your deployment will now have to wait for the data manipulation to be finished and that is just asking for trouble, with possible hanging or failed migrations.

Failed migrations are a problem, but this problem applies to all migrations, not just "data migrations". Any migration can fail and stop the deploy. That's why we test them first.

> [temporary rake tasks] give us more control of the data manipulation process by encapsulating it in one place.

This is really just bs. So a data migration is somehow in several places? Or not "encapsulated" enough, whatever that means.

Normally I agree with mr. Thoughtbot, but in this respect he is misinformed, or even making facts up.

You will of course do as you please @davidwessman but I don't think the arguments in that article are any good.

**Comment by davidwessman** [comment]
I definitely understand what your thinking.
Could you give an example of an migration data transfer?

I have a `CafeWork` model where I want to move `date, pass, lp` to `CafeShift` and a `user` to `CafeWorker` if it is present.

**Comment by jforberg** [comment]
The important thing is to do it in a transaction. I don't know how your models work so I'll just make up some code as an example.

CafeWork.transaction do
  CafeWork.all.each do |cw|
    cw.cafe_shift.update! :date => cw.date, :pass => cw.pass (...)
    cw.cafe_worker.update! :user => cw.user
  end
end

This would probably work, no? If you need it to go faster you can do it in plain SQL, but that would bypass validations.
